// src/productsData.js
const productsData = [
  {
    id: 1,
    name: "Apple",
    category: "Fruits",
    price: 120,
    stock: 30,
    description: "Fresh red apples 🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg",
  },
  {
    id: 2,
    name: "Carrot",
    category: "Vegetables",
    price: 60,
    stock: 50,
    description: "Organic carrots 🥕",
    image:
     "https://upload.wikimedia.org/wikipedia/commons/9/90/Hapus_Mango.jpg",
  },
  {
    id: 3,
    name: "Banana",
    category: "Fruits",
    price: 40,
    stock: 100,
    description: "Sweet ripe bananas 🍌",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg",
  },
  {
    id: 4,
    name: "Tomato",
    category: "Vegetables",
    price: 35,
    stock: 80,
    description: "Juicy red tomatoes 🍅",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg",
  },
  {
    id: 5,
    name: "Mango",
    category: "Fruits",
    price: 150,
    stock: 25,
    description: "Delicious summer mangoes 🥭",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/90/Hapus_Mango.jpg",
  },
  {
    id: 6,
    name: "Potato",
    category: "Vegetables",
    price: 30,
    stock: 120,
    description: "Fresh farm potatoes 🥔",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/64/Potato_with_sprouts.jpg",
  },
  {
    id: 7,
    name: "Orange",
    category: "Fruits",
    price: 90,
    stock: 60,
    description: "Citrusy sweet oranges 🍊",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c4/Orange-Fruit-Pieces.jpg",
  },
  {
    id: 8,
    name: "Broccoli",
    category: "Vegetables",
    price: 80,
    stock: 40,
    description: "Healthy green broccoli 🥦",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/03/Broccoli_and_cross_section_edit.jpg",
  },
  {
    id: 9,
    name: "Pineapple",
    category: "Fruits",
    price: 110,
    stock: 35,
    description: "Tropical juicy pineapples 🍍",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/cb/Pineapple_and_cross_section.jpg",
  },
  {
    id: 10,
    name: "Spinach",
    category: "Vegetables",
    price: 25,
    stock: 90,
    description: "Fresh green spinach leaves 🌿",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Spinacia_oleracea_Spinach_Leaves.jpg",
  },
  {
    id: 11,
    name: "Strawberry",
    category: "Fruits",
    price: 200,
    stock: 20,
    description: "Sweet red strawberries 🍓",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/29/PerfectStrawberry.jpg",
  },
  {
    id: 12,
    name: "Onion",
    category: "Vegetables",
    price: 45,
    stock: 70,
    description: "Fresh red onions 🧅",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/25/Onion_on_White.JPG",
  },
  {
    id: 13,
    name: "Papaya",
    category: "Fruits",
    price: 85,
    stock: 28,
    description: "Nutritious papayas 🥭",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6b/Papaya_cross_section_BNC.jpg",
  },
  {
    id: 14,
    name: "Cabbage",
    category: "Vegetables",
    price: 50,
    stock: 55,
    description: "Green healthy cabbage 🥬",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/2e/Cabbage_cross_section.jpg",
  },
  {
    id: 15,
    name: "Grapes",
    category: "Fruits",
    price: 130,
    stock: 45,
    description: "Fresh juicy grapes 🍇",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/36/Kyoho-grape.jpg",
  },
  {
    id: 16,
    name: "Cauliflower",
    category: "Vegetables",
    price: 70,
    stock: 38,
    description: "Fresh organic cauliflower 🌸",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Cauliflower.JPG",
  },
  {
    id: 17,
    name: "Guava",
    category: "Fruits",
    price: 60,
    stock: 48,
    description: "Delicious guavas 🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Guava_ID.jpg",
  },
  {
    id: 18,
    name: "Cucumber",
    category: "Vegetables",
    price: 40,
    stock: 77,
    description: "Fresh cucumbers 🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Cucumbers.jpg",
  },
  {
    id: 19,
    name: "Watermelon",
    category: "Fruits",
    price: 180,
    stock: 22,
    description: "Refreshing watermelons 🍉",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fd/Watermelon_cross_BNC.jpg",
  },
  {
    id: 20,
    name: "Brinjal",
    category: "Vegetables",
    price: 55,
    stock: 33,
    description: "Fresh purple brinjals 🍆",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Eggplant.jpg",
  },
  {
    id: 21,
    name: "Strawberry",
    category: "Fruits",
    price: 200,
    stock: 20,
    description: "Sweet red strawberries 🍓",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/29/PerfectStrawberry.jpg",
  },
  {
    id: 22,
    name: "Onion",
    category: "Vegetables",
    price: 45,
    stock: 70,
    description: "Fresh red onions 🧅",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/25/Onion_on_White.JPG",
  },
  {
    id: 23,
    name: "Papaya",
    category: "Fruits",
    price: 85,
    stock: 28,
    description: "Nutritious papayas 🥭",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6b/Papaya_cross_section_BNC.jpg",
  },
  {
    id: 24,
    name: "Cabbage",
    category: "Vegetables",
    price: 50,
    stock: 55,
    description: "Green healthy cabbage 🥬",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/2e/Cabbage_cross_section.jpg",
  },
  {
    id: 25,
    name: "Grapes",
    category: "Fruits",
    price: 130,
    stock: 45,
    description: "Fresh juicy grapes 🍇",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/36/Kyoho-grape.jpg",
  },
  {
    id: 26,
    name: "Cauliflower",
    category: "Vegetables",
    price: 70,
    stock: 38,
    description: "Fresh organic cauliflower 🌸",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Cauliflower.JPG",
  },
  {
    id: 27,
    name: "Guava",
    category: "Fruits",
    price: 60,
    stock: 48,
    description: "Delicious guavas 🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Guava_ID.jpg",
  },
  {
    id: 28,
    name: "Cucumber",
    category: "Vegetables",
    price: 40,
    stock: 77,
    description: "Fresh cucumbers 🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Cucumbers.jpg",
  },
  {
    id: 29,
    name: "Watermelon",
    category: "Fruits",
    price: 180,
    stock: 22,
    description: "Refreshing watermelons 🍉",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fd/Watermelon_cross_BNC.jpg",
  },
  {
    id: 30,
    name: "Brinjal",
    category: "Vegetables",
    price: 55,
    stock: 33,
    description: "Fresh purple brinjals 🍆",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Eggplant.jpg",
  },
];

export default productsData;
